In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
a = np.arange(1,101)
print(a)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [32]:
b = np.arange(500,600)
print(b)

[500 501 502 503 504 505 506 507 508 509 510 511 512 513 514 515 516 517
 518 519 520 521 522 523 524 525 526 527 528 529 530 531 532 533 534 535
 536 537 538 539 540 541 542 543 544 545 546 547 548 549 550 551 552 553
 554 555 556 557 558 559 560 561 562 563 564 565 566 567 568 569 570 571
 572 573 574 575 576 577 578 579 580 581 582 583 584 585 586 587 588 589
 590 591 592 593 594 595 596 597 598 599]


In [33]:
# split
# if using time series, want shuffle=False

train_test_split(a, b, test_size = 0.2, random_state=42)

[array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
         29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
         82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
         90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
         59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
         53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
         93,  52]),
 array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
        78, 13, 32]),
 array([555, 588, 526, 542, 569, 515, 540, 596, 509, 572, 511, 547, 585,
        528, 593, 505, 566, 565, 535, 516, 549, 534, 507, 595, 527, 519,
        581, 525, 562, 513, 524, 503, 517, 538, 508, 578, 506, 564, 536,
        589, 556, 599, 554, 543, 550, 567, 546, 568, 561, 597, 579, 541,
        558, 548, 598, 557, 575, 532, 594, 559, 563, 584, 537, 529, 501,
        552, 521, 502, 523, 587, 591, 574, 586, 582, 520, 560, 571, 514,
      

In [34]:
a_train, a_test = train_test_split(a)
b_train, b_test = train_test_split(b)

In [36]:
a_train.shape

(75,)

In [37]:
a_test.shape

(25,)

In [38]:
b_train

array([554, 593, 556, 568, 521, 529, 594, 588, 553, 512, 560, 519, 538,
       503, 571, 579, 539, 500, 562, 544, 545, 566, 576, 564, 572, 502,
       592, 543, 508, 526, 582, 522, 575, 557, 528, 527, 517, 599, 533,
       597, 520, 524, 537, 516, 590, 550, 541, 596, 507, 589, 586, 574,
       504, 573, 510, 580, 549, 531, 525, 555, 578, 569, 570, 551, 518,
       546, 585, 540, 581, 523, 505, 501, 577, 515, 530])

In [39]:
b_test

array([547, 535, 536, 591, 565, 542, 561, 595, 552, 511, 567, 534, 548,
       583, 558, 513, 506, 563, 559, 598, 509, 587, 514, 532, 584])

In [40]:
b_train.shape

(75,)

In [30]:
b_test.shape

(25,)

We have two different data sets ready for modeling and testing, allowing us to test for overfitting